#!/usr/bin/env python3
"""Extract frozen Brain-JEPA embeddings with explicit temporal-position policies."""

import argparse
import hashlib
import importlib.util
import json
from pathlib import Path

import numpy as np
import torch
from torch.utils.data import DataLoader


def find_ccn_root():
    for candidate in Path(__file__).resolve().parents:
        if (candidate / "CLAUDE.md").is_file() and (candidate / "study1").is_dir():
            return candidate
    raise RuntimeError("Could not locate the CCN project root")


ROOT = find_ccn_root()
EMOBRAIN_ROOT = next(parent for parent in ROOT.parents if parent.name == "EmoBrain")
SHARED_EXTRACTOR = (
    EMOBRAIN_ROOT / "project/shared/code/bfm_embeddings/_lib/brain_jepa.py"
)
CANONICAL_CSV = EMOBRAIN_ROOT / "project/shared/data/feelin_canonical_stimuli.csv"
CHECKPOINT = EMOBRAIN_ROOT / "external/checkpoints/brain_jepa/jepa-ep300.pth"


def load_shared_extractor():
    spec = importlib.util.spec_from_file_location("ccn_brain_jepa_source", SHARED_EXTRACTOR)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not import {SHARED_EXTRACTOR}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


SOURCE = load_shared_extractor()


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--subject", choices=[f"sub-{i:02d}" for i in range(1, 6)], required=True)
    parser.add_argument("--init", choices=["resting", "scratch"], default="resting")
    parser.add_argument(
        "--position-policy",
        choices=["native", "temporal_mean", "temporal_center"],
        default="native",
        help="How the 10-patch checkpoint temporal code is adapted to one patch.",
    )
    parser.add_argument(
        "--padding",
        choices=["mean", "zero", "replicate", "spatial_only", "cyclic_replicate"],
        default="mean",
    )
    parser.add_argument("--batch-size", type=int, default=32)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--seed", type=int, default=0)
    parser.add_argument("--smoke-test-n", type=int, default=None)
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument(
        "--output-root",
        type=Path,
        default=ROOT / "study1/data/brain_encoder_validation",
    )
    return parser.parse_args()


def tensor_hash(tensor):
    values = tensor.detach().cpu().contiguous().numpy()
    return hashlib.sha256(values.tobytes()).hexdigest()


def adapt_temporal_code(checkpoint_code, model_code, policy):
    n_rois = model_code.shape[0]
    if checkpoint_code.shape[0] % n_rois:
        raise ValueError(
            f"Checkpoint temporal code {tuple(checkpoint_code.shape)} is not divisible by {n_rois} ROIs"
        )
    n_time = checkpoint_code.shape[0] // n_rois
    code = checkpoint_code.reshape(n_rois, n_time, -1)
    if policy == "temporal_mean":
        return code.mean(dim=1), n_time
    if policy == "temporal_center":
        middle = [n_time // 2] if n_time % 2 else [n_time // 2 - 1, n_time // 2]
        return code[:, middle].mean(dim=1), n_time
    raise ValueError(f"No checkpoint adaptation is defined for {policy}")


def load_frozen_checkpoint(model, checkpoint_path, position_policy):
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    checkpoint_state = {
        key.replace("module.", "encoder."): value for key, value in checkpoint["encoder"].items()
    }
    model_state = model.state_dict()
    position_key = "encoder.pos_embed_proj.emb_h"
    patch_key = "encoder.patch_embed.proj.weight"

    if patch_key not in checkpoint_state or patch_key not in model_state:
        raise KeyError(f"Missing required checkpoint key: {patch_key}")
    if checkpoint_state[patch_key].shape != model_state[patch_key].shape:
        raise RuntimeError(
            "Patch embedding kernels do not match. This audit refuses to interpolate pretrained weights: "
            f"checkpoint={tuple(checkpoint_state[patch_key].shape)}, "
            f"model={tuple(model_state[patch_key].shape)}"
        )

    checkpoint_shape = tuple(checkpoint_state[position_key].shape)
    model_shape = tuple(model_state[position_key].shape)
    n_checkpoint_time_patches = checkpoint_shape[0] // model_shape[0]
    native_hash = tensor_hash(model_state[position_key])

    if position_policy == "native":
        # emb_h is fixed sin/cos code, not a learned checkpoint weight. Keep the
        # one-patch code generated by the one-patch model constructor.
        del checkpoint_state[position_key]
    else:
        adapted, n_checkpoint_time_patches = adapt_temporal_code(
            checkpoint_state[position_key], model_state[position_key], position_policy
        )
        if adapted.shape != model_state[position_key].shape:
            raise RuntimeError(
                f"Adapted temporal code has shape {tuple(adapted.shape)}, expected {model_shape}"
            )
        checkpoint_state[position_key] = adapted

    message = model.load_state_dict(checkpoint_state, strict=False)
    # The downstream global-pooling wrapper adds a final LayerNorm that is not
    # present in the self-supervised encoder checkpoint. Its deterministic default
    # is weight=1, bias=0.
    allowed_missing = {"head.weight", "head.bias", "fc_norm.weight", "fc_norm.bias"}
    if position_policy == "native":
        allowed_missing.add(position_key)
    disallowed_missing = sorted(set(message.missing_keys) - allowed_missing)
    if disallowed_missing or message.unexpected_keys:
        raise RuntimeError(
            f"Checkpoint load mismatch: missing={disallowed_missing}, "
            f"unexpected={message.unexpected_keys}"
        )

    loaded_hash = tensor_hash(model.state_dict()[position_key])
    if position_policy == "native" and loaded_hash != native_hash:
        raise RuntimeError("Native temporal code changed during checkpoint loading")

    return {
        "checkpoint_position_shape": checkpoint_shape,
        "model_position_shape": model_shape,
        "checkpoint_time_patches": int(n_checkpoint_time_patches),
        "checkpoint_patch_shape": tuple(checkpoint_state[patch_key].shape),
        "model_patch_shape": tuple(model_state[patch_key].shape),
        "position_code_trainable": bool(model_state[position_key].requires_grad),
        "position_code_sha256": loaded_hash,
        "missing_keys": list(message.missing_keys),
        "unexpected_keys": list(message.unexpected_keys),
    }


def main():
    args = parse_args()
    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = torch.device(args.device)

    dataset = SOURCE.EmoBrainHorikawaJEPADataset(
        args.subject, padding=args.padding, canonical_csv=CANONICAL_CSV
    )
    if args.smoke_test_n is not None:
        dataset.stim_names = dataset.stim_names[: args.smoke_test_n]
        dataset.stim_nums = dataset.stim_nums[: args.smoke_test_n]

    loader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=device.type == "cuda",
        collate_fn=SOURCE.collate,
    )

    model = SOURCE.build_model(device, attn_mode="normal")
    audit = {
        "checkpoint_position_shape": None,
        "model_position_shape": tuple(model.state_dict()["encoder.pos_embed_proj.emb_h"].shape),
        "checkpoint_time_patches": None,
        "checkpoint_patch_shape": None,
        "model_patch_shape": tuple(model.state_dict()["encoder.patch_embed.proj.weight"].shape),
        "position_code_trainable": False,
        "missing_keys": [],
        "unexpected_keys": [],
    }
    if args.init == "resting":
        audit = load_frozen_checkpoint(model, CHECKPOINT, args.position_policy)
    elif args.position_policy != "native":
        raise ValueError("Scratch models have no checkpoint temporal code to adapt; use --position-policy native")

    model.head = torch.nn.Identity()
    model.to(device).eval()
    embeddings, stim_nums, padding_ratios, original_times = [], [], [], []
    with torch.no_grad():
        for batch_i, batch in enumerate(loader):
            output = model(batch["fmri"].to(device, non_blocking=True))
            if isinstance(output, tuple):
                output = output[0]
            embeddings.append(output.detach().cpu().numpy().astype(np.float32))
            stim_nums.append(batch["stim_num"])
            padding_ratios.append(batch["padding_ratio"])
            original_times.append(batch["original_T"])
            if (batch_i + 1) % 10 == 0 or batch_i + 1 == len(loader):
                print(f"batch {batch_i + 1}/{len(loader)}")

    embeddings = np.concatenate(embeddings)
    stim_nums = np.concatenate(stim_nums)
    padding_ratios = np.concatenate(padding_ratios)
    original_times = np.concatenate(original_times)
    if not np.isfinite(embeddings).all():
        raise ValueError("Extracted embeddings contain NaN or Inf")

    run_name = f"brain_jepa_{args.init}_pos-{args.position_policy}_pad-{args.padding}"
    if args.smoke_test_n is not None:
        output_dir = args.output_root / "smoke" / run_name
    else:
        output_dir = args.output_root / "embeddings" / run_name
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"{args.subject}.pt"
    metadata = {
        "subject": args.subject,
        "init": args.init,
        "position_policy": args.position_policy,
        "padding": args.padding,
        "num_frames": SOURCE.NUM_FRAMES,
        "n_rois": SOURCE.N_ROIS,
        "seed": args.seed,
        "checkpoint": str(CHECKPOINT) if args.init == "resting" else None,
        "source_extractor": str(SHARED_EXTRACTOR),
        "canonical_csv": str(CANONICAL_CSV),
        "audit": audit,
    }
    payload = {
        "embeddings": torch.from_numpy(embeddings),
        "stim_num": torch.from_numpy(stim_nums),
        "padding_ratio": torch.from_numpy(padding_ratios),
        "original_T": torch.from_numpy(original_times),
        **metadata,
    }
    torch.save(payload, output_path)
    np.savez_compressed(
        output_path.with_suffix(".npz"),
        embeddings=embeddings,
        stim_num=stim_nums,
        padding_ratio=padding_ratios,
        original_T=original_times,
    )
    with open(output_path.with_suffix(".json"), "w", encoding="utf-8") as handle:
        json.dump(metadata, handle, indent=2)

    print(f"Saved: {output_path}")
    print(f"Shape: {embeddings.shape}")
    print(f"Mean padding ratio: {padding_ratios.mean():.4f}")
    print(f"Position policy: {args.position_policy}")
    print(f"Position code trainable: {audit['position_code_trainable']}")


if __name__ == "__main__":
    main()
